blank_issues_enabled: false
contact_links:
  - name: Security reports
    url: https://github.com/DipesThapa/safebrowse-ai/security/advisories/new
    about: Please report security vulnerabilities privately via GitHub advisories.
