name: Release
on:
  push:
    tags: ['v*']
permissions:
  contents: write
jobs:
  build-zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Create zip
        run: |
          ZIP="safeguard-${GITHUB_REF_NAME}.zip"
          echo "ZIP_FILE=$ZIP" >> $GITHUB_ENV
          zip -r "$ZIP" . -x ".git/*" ".github/*" "node_modules/*" "*.zip"
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Safeguard ${{ github.ref_name }}
          files: ${{ env.ZIP_FILE }}
